const descriptions: { [key: string]: Record<string, string> } = {
	Home: {
		ru: "ALP.COM — европейская платформа обмена криптовалюты. Здесь можно обменять и купить биткоины на лучшей бирже криптовалют. Мы обеспечиваем быстрый ввод и вывод средств. Cамые свежие новости и аналитика криптовалют.",
		en: "ALP.COM is the European cryptocurrency exchange platform. Here you can buy and sell cryptocurrency on the best cryptocurrency exchange. Enjoy trading and learn how to trade cryptocurrency. Read cryptocurrency news today.",
		de: "ALP.COM ist die europäische Plattform für den Austausch von Kryptowährungen. Hier können Sie Kryptowährung an der besten Kryptowährungsbörse kaufen und verkaufen. Viel Spaß beim Handeln und lernen Sie, wie man mit Kryptowährung handelt. Lesen Sie noch heute Kryptowährungsnachrichten.",
		es: "ALP.COM es la plataforma europea de intercambio de criptomonedas. Aquí puede comprar y vender criptomonedas en el mejor intercambio de criptomonedas. Disfrute comerciando y aprenda a comerciar con criptomonedas. Lea las noticias sobre criptomonedas hoy.",
		pt: "ALP.COM é a plataforma europeia de câmbio de criptomoedas. Aqui você pode comprar e vender criptomoedas na melhor bolsa de criptomoedas. Desfrute da negociação e aprenda como negociar criptomoeda. Leia notícias sobre criptomoedas hoje.",
		zh: "BTC-Alpha是欧洲加密货币交换平台。在这里，您可以在最好的加密货币交易所上买卖加密货币。享受交易并学习如何交易加密货币。立即阅读加密货币新闻。",
		hi: "बीटीसी-अल्फा यूरोपीय क्रिप्टोक्यूरेंसी एक्सचेंज प्लेटफॉर्म है। यहां आप क्रिप्टोक्यूरेंसी को सर्वश्रेष्ठ क्रिप्टोक्यूरेंसी एक्सचेंज पर खरीद और बेच सकते हैं। ट्रेडिंग का आनंद लें और जानें कि कैसे क्रिप्टोकरेंसी का व्यापार करें। आज क्रिप्टोक्यूरेंसी समाचार पढ़ें।",
		fr: "ALP.COM est la plateforme européenne d'échange de crypto-monnaie. Ici, vous pouvez acheter et vendre de la crypto-monnaie sur le meilleur échange de crypto-monnaie. Profitez du trading et apprenez à trader la crypto-monnaie. Lisez les nouvelles de la crypto-monnaie aujourd'hui.",
		uk: "ALP.COM — європейська платформа обміну криптовалют. Тут ви можете купувати та продавати криптовалюту на кращій біржі криптовалют. Насолоджуйтесь торгівлею та навчіться торгувати криптовалютою. Читайте новини про криптовалюту сьогодні.",
	},
	Demo: {
		ru: "ALP.COM Демо-Трейдинг — курс обучения криптотрейдингу с нуля. Попробовать криптотрейдинг для начинающих. Большой выбор виртуальных пар для обучения. ",
		en: "ALP.COM Demo Trading is for those who want to study how to trade cryptocurrency. Discover crypto trading strategy today. Use virtual pairs for trading safely. Start your crypto trading learning course today.",
		de: "ALP.COM Demo Trading ist für diejenigen gedacht, die lernen möchten, wie man mit Kryptowährung handelt. Entdecken Sie noch heute die Krypto-Handelsstrategie. Verwenden Sie virtuelle Paare, um sicher zu handeln. Starten Sie noch heute Ihren Krypto-Trading-Lernkurs.",
		es: "ALP.COM Demo Trading es para aquellos que desean estudiar cómo operar con criptomonedas. Descubra la estrategia de comercio de cifrado hoy. Utilice pares virtuales para operar de forma segura. Comience hoy mismo su curso de aprendizaje sobre comercio de cifrado.",
		pt: "O ALP.COM Demo Trading é para aqueles que querem estudar como negociar criptomoedas. Descubra a estratégia de negociação de criptografia hoje. Use pares virtuais para negociar com segurança. Comece seu curso de aprendizagem de negociação de criptografia hoje.",
		zh: "BTC-Alpha演示交易适合那些想学习如何交易加密货币的人。立即发现加密交易策略。使用虚拟货币对进行安全交易。立即开始您的加密货币交易学习课程。",
		hi: "बीटीसी-अल्फा डेमो ट्रेडिंग उन लोगों के लिए है जो क्रिप्टोक्यूरेंसी का व्यापार करना चाहते हैं। आज क्रिप्टो ट्रेडिंग रणनीति की खोज करें। सुरक्षित रूप से व्यापार करने के लिए आभासी जोड़े का उपयोग करें। आज ही अपना क्रिप्टो ट्रेडिंग लर्निंग कोर्स शुरू करें।",
		fr: "ALP.COM Demo Trading est destiné à ceux qui souhaitent étudier comment échanger des crypto-monnaies. Découvrez la stratégie de crypto trading aujourd'hui. Utilisez des paires virtuelles pour trader en toute sécurité. Commencez votre cours d'apprentissage sur le crypto trading dès aujourd'hui.",
		uk: "Демо-Трейдинг ALP.COM призначений для тих, хто хоче вивчити, як торгувати криптовалютою. Розкрийте стратегію торгівлі криптовалютами вже сьогодні. Використовуйте віртуальні пари для торгівлі безпечно. Почніть свій курс навчання з торгівлі криптовалютами вже сьогодні.",
	},
	BuyCrypto: {
		ru: "Покупка криптовалюты на ALP.COM позволяет купить криптовалюту с помощью кредитной карты или кошелька для криптовалюты в 1 клик. Лучшие торговые инструменты, чтобы купить 10 лучших криптовалют сегодня.",
		en: "Purchase of cryptocurrency on ALP.COM. Buy cryptocurrency with credit card or cryptocurrency wallet easily. Best trading tools to buy TOP-10 cryptocurrencies today.",
		de: "Kauf von Kryptowährung auf ALP.COM. Kaufen Sie Kryptowährung einfach mit Kreditkarte oder Kryptowährungsgeldbörse. Die besten Handelstools, um heute TOP-10-Kryptowährungen zu kaufen.",
		es: "Compra de criptomonedas en ALP.COM. Compre criptomonedas con tarjeta de crédito o billetera de criptomonedas fácilmente. Las mejores herramientas comerciales para comprar criptomonedas TOP-10 hoy.",
		pt: "Compra de criptomoeda no ALP.COM. Compre criptomoeda com cartão de crédito ou carteira de criptomoeda facilmente. As melhores ferramentas de negociação para comprar criptomoedas TOP-10 hoje.",
		zh: "在BTC-Alpha上购买加密货币。使用信用卡或加密货币钱包轻松购买加密货币。今天购买TOP-10加密货币的最佳交易工具。",
		hi: "बीटीसी-अल्फा पर क्रिप्टोकरेंसी की खरीद। क्रिप्टोकरेंसी को क्रेडिट कार्ड या क्रिप्टोक्यूरेंसी वॉलेट से आसानी से खरीदें। आज टॉप -10 क्रिप्टोकरेंसी खरीदने के लिए बेस्ट ट्रेडिंग टूल।",
		fr: "Achat de crypto-monnaie sur ALP.COM. Achetez facilement de la crypto-monnaie avec une carte de crédit ou un portefeuille de crypto-monnaie. Meilleurs outils de trading pour acheter les crypto-monnaies TOP-10 aujourd'hui.",
		uk: "Купівля криптовалюти на ALP.COM. Купуйте криптовалюту за допомогою кредитної картки або гаманця криптовалюти легко. Найкращі трейдерські інструменти для придбання ТОП-10 криптовалют.",
	},
	Listing: {
		ru: "Листинг на ALP.COM для добавления ваших токенов и монет на биржу. Необходимые условия для листинга монет. Лучшее время, чтобы добавить монету на биржу уже сейчас.",
		en: "Listing ALP.COM is the procedure of including a coin/token in the list of crypto assets admitted to trading. Project requirements for token/coin listing. Get listed easily today on ALP.COM.",
		de: "Bei der Auflistung von ALP.COM wird eine Münze / ein Token in die Liste der zum Handel zugelassenen Krypto-Assets aufgenommen. Projektanforderungen für die Auflistung von Token / Münzen. Holen Sie sich noch heute einfach auf ALP.COM gelistet.\n",
		es: "Enumerar ALP.COM es el procedimiento de incluir una moneda / ficha en la lista de activos criptográficos admitidos a negociación. Requisitos del proyecto para el listado de fichas / monedas. Inscríbase fácilmente hoy en ALP.COM.",
		pt: "Listar ALP.COM é o procedimento de inclusão de uma moeda / token na lista de ativos criptográficos admitidos à negociação. Requisitos do projeto para listagem de tokens / moedas. Seja listado facilmente hoje no ALP.COM.",
		zh: "列出BTC-Alpha是将硬币/代币包括在允许交易的加密资产列表中的过程。代币/硬币清单的项目要求。立即在BTC-Alpha上轻松列出。",
		hi: "बीटीसी-अल्फा को सूचीबद्ध करना व्यापार में भर्ती होने वाली क्रिप्टो परिसंपत्तियों की सूची में एक सिक्का / टोकन शामिल करने की प्रक्रिया है। टोकन / सिक्का लिस्टिंग के लिए परियोजना की आवश्यकताएं। बीटीसी-अल्फा पर आज आसानी से सूचीबद्ध हो जाओ।",
		fr: "La cotation de ALP.COM est la procédure d'inclusion d'une pièce / d'un jeton dans la liste des actifs cryptographiques admis à la négociation. Exigences du projet pour la liste des jetons / pièces. Inscrivez-vous facilement dès aujourd'hui sur ALP.COM.",
		uk: "Лістинг ALP.COM — це процедура включення монети / токена до списку криптовалют, допущених до торгів. Вимоги проекту до лістингу токенів / монет. Отримати лістинг легко сьогодні на ALP.COM.\n",
	},
	SocialListing: {
		ru: "Социальный листинг ALP.COM — возможность бесплатной интеграции монеты или токена на биржу с помощью поддержки пользователей. Условия голосования и добавления монеты на биржу. Интегрировать монету бесплатно",
		en: "ALP.COM Social Listing is the opportunity to integrate a coin or token into the crypto exchange with the help of user support. Conditions for voting and adding a coin to the ALP.COM exchange. Integrate your coin for free.",
		de: "ALP.COM Social Listing bietet die Möglichkeit, mithilfe der Benutzerunterstützung eine Münze oder einen Token in den Krypto-Austausch zu integrieren. Bedingungen für die Abstimmung und das Hinzufügen einer Münze zur ALP.COM-Börse. Integrieren Sie Ihre Münze kostenlos.\n",
		es: "El listado social ALP.COM es la oportunidad de integrar una moneda o token en el intercambio de cifrado con la ayuda del soporte del usuario. Condiciones para votar y agregar una moneda al intercambio ALP.COM. Integra tu moneda gratis.",
		pt: "A Listagem Social ALP.COM é a oportunidade de integrar uma moeda ou token na troca de criptografia com a ajuda do suporte ao usuário. Condições de votação e adição de moeda à bolsa ALP.COM. Integre sua moeda gratuitamente.",
		zh: "BTC-Alpha社交列表是在用户支持的帮助下将硬币或代币集成到加密货币交易所中的机会。投票和向BTC-Alpha交易所添加硬币的条件。免费整合您的硬币。",
		hi: "बीटीसी-अल्फा सोशल लिस्टिंग एक सिक्का या टोकन को उपयोगकर्ता के समर्थन की मदद से क्रिप्टो एक्सचेंज में एकीकृत करने का अवसर है। वोट देने और बीटीसी-अल्फा एक्सचेंज में एक सिक्का जोड़ने की शर्तें। अपने सिक्के को मुफ्त में एकीकृत करें।",
		fr: "ALP.COM Social Listing est l'opportunité d'intégrer une pièce ou un jeton dans l'échange crypto avec l'aide du support utilisateur. Conditions pour voter et ajouter une pièce à l'échange ALP.COM. Intégrez votre pièce gratuitement.",
		uk: "ALP.COM Соціальний Лістинг — це можливість інтегрувати монету чи токен на біржі за допомогою підтримки користувачів. Умови голосування та додавання монети на біржу ALP.COM. Інтегруйте монету безкоштовно.",
	},
	CoinInfo: {
		ru: "Информация о монетах на ALP.COM: Bitcoin, ETH, LTC, альткойны и другие основные криптовалюты. Узнайте, в какую криптовалюту инвестировать в 2020 году.",
		en: "ALP.COM Coin Info with coin information list: Bitcoin, ETH, altcoins, other major cryptocurrencies. Find out what cryptocurrency to invest in 2020.",
		de: "ALP.COM Coin Info mit Münzinformationsliste: Bitcoin, ETH, Altcoins, andere wichtige Kryptowährungen. Finden Sie heraus, in welche Kryptowährung Sie 2020 investieren sollen.",
		es: "ALP.COM Coin Info con lista de información de monedas: Bitcoin, ETH, altcoins, otras criptomonedas importantes. Descubra en qué criptomoneda invertir en 2020.",
		pt: "ALP.COM Coin Info com lista de informações de moedas: Bitcoin, ETH, altcoins, outras criptomoedas importantes. Descubra em qual criptomoeda investir em 2020.\n",
		zh: "带有硬币信息列表的BTC-Alpha硬币信息：比特币，ETH，山寨币，其他主要加密货币。找出2020年要投资的加密货币。",
		hi: "BTC- अल्फा कॉइन इन्फो विद कॉइन सूचना सूची: बिटकॉइन, ETH, altcoins, अन्य प्रमुख क्रिप्टोकरेंसी। 2020 में निवेश करने के लिए क्रिप्टोक्यूरेंसी का पता लगाएं।\n",
		fr: "ALP.COM Coin Info avec liste d'informations sur les pièces: Bitcoin, ETH, altcoins, autres principales crypto-monnaies. Découvrez quelle crypto-monnaie investir en 2020.",
		uk: "Інформація про монети на ALP.COM: Bitcoin, ETH, LTC, альткойни та інші основні криптовалюти. Дізнайтеся, в яку криптовалюту інвестувати в 2020 році.",
	},
};

export default descriptions;
